
[functions.purchase-copy-contract]
enabled = true
verify_jwt = true
import_map = "./functions/purchase-copy-contract/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/purchase-copy-contract/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/purchase-copy-contract/*.html" ]

[functions.subscribe-trading-signals]
enabled = true
verify_jwt = true
import_map = "./functions/subscribe-trading-signals/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/subscribe-trading-signals/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/subscribe-trading-signals/*.html" ]

[functions.purchase-course]
enabled = true
verify_jwt = true
import_map = "./functions/purchase-course/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/purchase-course/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/purchase-course/*.html" ]
